version: "3.9"

services:
  laba6:
    depends_on:
      - postgres
    image: ramon1634/test1
    ports:
      - "8080:8080"
    environment:
      DB_PASS: DisKretka321
      DB_NAME: Laba6
      DB_URL: postgres
  postgres:
    image: postgres:14.3-alpine3.16
    restart: unless-stopped
    environment:
      POSTGRES_DB: Laba6
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: DisKretka321
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
volumes:
  postgres_data:
    driver: local